version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
  postgres:
    image: 'postgres:9.5'
    restart: always
    environment:
      POSTGRES_PASSWORD: devpass
    ports:
      - '5436:5432'

volumes:
  redis_data:
    driver: local
