basePath: /
definitions: {}
info:
    license:
        name: MIT
    title: tipapp-api
    version: 0.0.1
paths:
    /ping:
        get:
            operationId: PingSayPong
            produces:
                - text/html
            responses:
                '200':
                    description: Ok
                    schema:
                        type: string
            description: ""
            parameters: []
    /login:
        post:
            operationId: LoginLogin
            produces:
                - text/html
            responses:
                '200':
                    description: Ok
                    schema:
                        type: string
            description: ""
            consumes:
                - application/x-www-form-urlencoded
            parameters:
                -
                    description: ""
                    in: formData
                    name: username
                    required: true
                    type: string
                -
                    description: ""
                    in: formData
                    name: password
                    required: true
                    type: string
    /register:
        post:
            operationId: LoginRegister
            produces:
                - text/html
            responses:
                '200':
                    description: Ok
                    schema:
                        type: string
            description: ""
            consumes:
                - application/x-www-form-urlencoded
            parameters:
                -
                    description: ""
                    in: formData
                    name: email
                    required: true
                    type: string
                -
                    description: ""
                    in: formData
                    name: username
                    required: true
                    type: string
                -
                    description: ""
                    in: formData
                    name: firstname
                    required: true
                    type: string
                -
                    description: ""
                    in: formData
                    name: lastname
                    required: true
                    type: string
                -
                    description: ""
                    in: formData
                    name: password
                    required: true
                    type: string
    /api/users:
        get:
            operationId: UsersGetUsers
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        type: array
                        items:
                            type: object
            description: ""
            parameters: []
    '/api/users/{id}':
        get:
            operationId: UsersGetUser
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        type: object
            description: ""
            parameters:
                -
                    description: ""
                    in: path
                    name: id
                    required: true
                    type: number
                    format: double
swagger: '2.0'
securityDefinitions: {}
